services:
  - type: web
    name: peer-evaluation-presentations-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20.19.0"
      - key: TEACHER_PIN
        sync: false
